[package]
name = "neural_ascii"
version = "0.1.0"
edition = "2024"



[dependencies]
ndarray = "0.15"
mnist = "0.6.0"
clap = { version = "4.0", features = ["derive"] }
ndarray-rand = "0.14"
rand = "0.8"
rand_distr = "0.4"
serde_json = "1.0"


